name: "Push changes do nodejs app"

on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
    paths:
      - 'src/**'


jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v4


      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add hosts to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H your.server.example >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Push changes using ansible
        run: |
          ansible-playbook playbook.yml -t nodejs
        working-directory: ./ansible
